### ISSUE TITLE
Blender 2.78: Unable to install - no module named 'PIL'

### ISSUE THREAD

**Issue by Trimatix** [doakey3/Bizualizer#1]
Hiya. I'm in Blender version 2.78. After installing from file, I can't enable the add-on, due to the error in the attached screenshot.
![capture](https://user-images.githubusercontent.com/3754670/29488870-75a7cc6a-850b-11e7-9744-6c489f8a8965.PNG)

**Comment by Trimatix** [comment]
Might want to look at this: https://stackoverflow.com/questions/8863917/importerror-no-module-named-pil

**Comment by doakey3** [comment]
I added a Batch mode function that requires a couple libraries (pillow and mutagen). The rest of the addon doesn't need them.

I think I just fixed your issue by disabling the parts of the addon that require those libraries unless you have them installed. Please try it and let me know if you're still having an issue.

**Comment by Trimatix** [comment]
That's much better, thanks!
