### ISSUE TITLE
Scene object has no attribute collection

### ISSUE THREAD

**Issue by bark4mark** [doakey3/Bizualizer#2]
![error](https://user-images.githubusercontent.com/4677277/50923157-2bff6400-1444-11e9-87fc-f55513b714ca.png)

I am having a small problem trying to generate the visualizer. I am using version 2.79, I am following the tutorial on https://www.youtube.com/watch?v=8mskAiSiEjk.

If you could point me in the right direction to fixing I can open a pull request.

Thank you 😄

**Comment by doakey3** [comment]
You are using version 1.2.4 on Blender 2.79. It won't work because it is designed for Blender 2.80. If you want to use Blender 2.79, you'll need to use Subsimport version 1.2.3
